version: '3.8'

services:
  web:
    build: .
    container_name: easeops
    ports:
      - "8000:5000"
    env_file:
      - production.env
    environment:
      - ENV_FILE=production.env
    
    dns:
      - 8.8.8.8

