version: '3.8'

services:
  web:
    build: .
    container_name: easeops
    ports:
      - "8000:5000"
    env_file:
      - production.env
    environment:
      - ENV_FILE=production.env
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: gron
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
